name: crdt_draw
description: A collaborative real-time local-first global canvas (server)
version: 1.0.0
repository: https://github.com/cachapa/crdt_draw

environment:
  sdk: ^3.1.2

dependencies:
  crdt: ^5.1.2
#    path: ../crdt
  crdt_sync: ^1.0.6
#    path: ../../crdt_sync

dev_dependencies:
  http: any
  lints: any
  test: any
